"""
Script to generate catalogs/core_decays.yaml from the PDG Python API.

Run with:
    python -m hadron_anki.catalog.generate_core_decays

Or directly:
    python src/hadron_anki/catalog/generate_core_decays.py
"""
from __future__ import annotations

import sys
from pathlib import Path

# Ensure src/ is on path when run directly
SRC = Path(__file__).parent.parent.parent.parent
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC / "src"))

from hadron_anki.catalog.bootstrap_decays import bootstrap_all_decays

CORE_PARTICLE_IDS = [
    "proton", "neutron",
    "pi_plus", "pi_minus", "pi_zero",
    "k_plus", "k_minus", "k_zero",
    "lambda_0",
    "sigma_plus", "sigma_zero", "sigma_minus",
    "xi_zero", "xi_minus",
    "omega_minus",
]

OUTPUT_PATH = Path(__file__).parent.parent.parent.parent / "catalogs" / "core_decays.yaml"


def _render_yaml(results: dict) -> str:
    lines = [
        "# core_decays.yaml",
        "# Auto-generated by src/hadron_anki/catalog/generate_core_decays.py",
        "# Source: PDG Python API 2025  (https://pdg.lbl.gov/api)",
        "# DO NOT EDIT BY HAND — re-run the generator to update.",
        "",
    ]
    for repo_id in sorted(results.keys()):
        entry = results[repo_id]
        lines.append(f"{repo_id}:")
        if entry["stable"]:
            lines.append("  stable: true")
        else:
            lines.append("  stable: false")
            dr = entry.get("main_decay")
            if dr:
                children_str = ", ".join(f'"{c}"' for c in dr.children)
                lines.append("  main_decay:")
                lines.append(f'    parent: "{dr.parent}"')
                lines.append(f"    children: [{children_str}]")
                lines.append(f"    branching_ratio: {dr.branching_ratio:.6g}")
                lines.append(f'    description: "{dr.description}"')
                lines.append(f'    source: "{dr.source}"')
                lines.append(f'    source_kind: "{dr.source_kind}"')
            else:
                lines.append("  main_decay: null")
                lines.append(f"  note: \"No exclusive BF data available (raw_bf={entry['raw_bf_count']})\"")
        lines.append("")
    return "\n".join(lines)


def _print_report(results: dict) -> None:
    stable = [k for k, v in results.items() if v["stable"]]
    unstable = [k for k, v in results.items() if not v["stable"]]
    with_decay = [k for k in unstable if results[k].get("main_decay")]
    without_decay = [k for k in unstable if not results[k].get("main_decay")]

    print("\n" + "=" * 60)
    print("DECAY BOOTSTRAP REPORT")
    print("=" * 60)
    print(f"\nStable particles ({len(stable)}): {', '.join(stable)}")
    print(f"\nUnstable particles ({len(unstable)}):")
    for pid in unstable:
        dr = results[pid].get("main_decay")
        sk = results[pid].get("source_kind", "?")
        if dr:
            ch = " + ".join(dr.children)
            print(f"  {pid:20s}  ->  {ch}  (BR={dr.branching_ratio:.4f})  [{sk}]")
        else:
            bfc = results[pid].get("raw_bf_count", 0)
            print(f"  {pid:20s}  ->  [NO DATA]  (raw_bf={bfc})  [{sk}]")

    if without_decay:
        print(f"\n⚠ Particles without dominant decay data: {', '.join(without_decay)}")

    print(f"\nSource path used: {results[unstable[0]]['source_kind'] if unstable else 'N/A'}")
    print("=" * 60)


def main() -> None:
    print(f"Bootstrapping decay data for {len(CORE_PARTICLE_IDS)} particles...")
    results = bootstrap_all_decays(CORE_PARTICLE_IDS)

    _print_report(results)

    yaml_str = _render_yaml(results)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(yaml_str, encoding="utf-8")
    print(f"\nWritten to: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
